blank_issues_enabled: true
contact_links:
  - name: Victron Community - modification space
    url: https://community.victronenergy.com/spaces/31/index.html
    about: Victron Community - modification space
